[package]
name = "rvm"
version = "0.1.0"
authors = ["ever"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
log = "0.4.8"
env_logger = "0.7.1"
byteorder = "1.3.4"
